credentials:
  cookie:
    key: ''
    secret: ''
  facebook:
    key:    ''
    secret: ''
  twitter:
    key:    ''
    secret: ''
  courier:
    address:  ''
    port:     ''
    key:      ''
    secret:   ''
